version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secure_pass_here
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    container_name: 'image-resizer-api'
    build: .
    depends_on:
      db:
        condition: service_healthy 
    ports:
      - "3000:3000"
