version: '3'
services:
  db:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=secure_pass_here
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    volumes:
      - './output:/api/output'
    depends_on:
      db:
        condition: service_healthy 
    environment:
      - NODE_ENV=development
      - PORT=3000
      - AZURE_IMAGE_RESIZER_HOST=resizer-service
      - SERVICE_NAME=api
      - AZURE_CODE=HjbLPb0S71628Zzj41OEpDhaMctR0H7EupI1Sosq-x_KAzFuk2Hxrw==
    ports:
      - "3000:3000"
  resizer-service:
    build: ./azure-resizer
    ports:
      - "8080:80"
