export const TOKENS = {
    IMAGE_REPOSITORY: 'IMAGE_REPOSITORY',
    TASK_REPOSITORY: 'TASK_REPOSITORY',
    IMAGE_RESIZER: 'IMAGE_RESIZER',
    AZURE_CODE: 'AZURE_CODE',
}

export const requiredSizes = [800, 1000];